model:
  target: model.model.PIQModel
  params:
    head: linear
    lr: 1e-4

data:
  target: dataset.piq.PIQDataModule
  params:
    batch_size: 32
    num_workers: 2

loggers:
  tensorboard:
    target: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: logs
      name: piq
  wandb:
    target: pytorch_lightning.loggers.WandbLogger
    params:
      name: pq
      project: piq

callbacks:
  model_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      monitor: val_loss
      mode: min
      save_top_k: 1
      save_last: True
      filename: '{epoch}-{val_loss:.2f}'

  lr_monitor:
    target: pytorch_lightning.callbacks.LearningRateMonitor
    params:
      logging_interval: 'step'

  # memory:
  #   target: pytorch_lightning.callbacks.DeviceStatsMonitor

trainer:
  target: pytorch_lightning.Trainer
  params:
    accelerator: gpu
    devices: 1
    precision: 16
    log_every_n_steps: 5
    max_epochs: 20
    num_sanity_val_steps: 0