name: resnet50
model:
  target: model.base.BasePIQModel
  params:
    lr: 1e-5
    freeze_backbone: false
  backbone:
    target: model.backbone.resnet50_backbone
    params:
      pretrained: true

loggers:
  tensorboard:
    target: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: logs
      name: ${name}
  wandb:
    target: pytorch_lightning.loggers.WandbLogger
    params:
      name: ${name}
      group: resnet
      project: piq